name: scentedbyk
favicon: null
layout_spectrum: 0.9286789561156183
typography_spectrum: 0.014097507111728191
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.18753286311402917
  lightness: 0.17911178176291287
  saturation: 0.3628192264586687
  rhythmicContrast: 0.48161832871846855
purpose: []
